use std::ffi::c_void;
use std::net::IpAddr;

use scylla::policies::host_listener::{HostEvent, HostEventContext, HostListener};

use crate::{
    cass_host_listener_types::{CassHostListenerEvent, CassInet},
    cql_types::inet::CassInetLength,
};

/// Same as [CassHostListenerCallback](crate::cass_host_listener_types::CassHostListenerCallback),
/// but non-nullable.
pub(crate) type CassHostListenerNonnullableCallback =
    unsafe extern "C" fn(event: CassHostListenerEvent, address: CassInet, data: *mut c_void);

/// A [HostListener] implementation that calls a C callback on host events.
///
/// Compatible with [cass_cluster_set_host_listener_callback](crate::cluster::cass_cluster_set_host_listener_callback).
pub(crate) struct CCallbackBasedHostListener {
    callback: CassHostListenerNonnullableCallback,
    data: *mut c_void,
}

impl CCallbackBasedHostListener {
    pub(crate) fn new(callback: CassHostListenerNonnullableCallback, data: *mut c_void) -> Self {
        Self { callback, data }
    }
}

unsafe impl Send for CCallbackBasedHostListener {}
unsafe impl Sync for CCallbackBasedHostListener {}

impl HostListener for CCallbackBasedHostListener {
    fn on_event(&self, context: &HostEventContext, event: &HostEvent) {
        let ip = context.addr().ip();
        let cass_addr = CassInet::from(ip);

        match event {
            HostEvent::Added => unsafe {
                (self.callback)(
                    CassHostListenerEvent::CASS_HOST_LISTENER_EVENT_ADD,
                    cass_addr,
                    self.data,
                );
            },
            HostEvent::Removed => unsafe {
                (self.callback)(
                    CassHostListenerEvent::CASS_HOST_LISTENER_EVENT_REMOVE,
                    cass_addr,
                    self.data,
                );
            },
            HostEvent::Up => unsafe {
                (self.callback)(
                    CassHostListenerEvent::CASS_HOST_LISTENER_EVENT_UP,
                    cass_addr,
                    self.data,
                );
            },
            HostEvent::Down => unsafe {
                (self.callback)(
                    CassHostListenerEvent::CASS_HOST_LISTENER_EVENT_DOWN,
                    cass_addr,
                    self.data,
                );
            },
            HostEvent::AddressChanged {
                old_address,
                new_address,
            } => {
                // Special case: node changed its address. We need to call the callback twice: once for removal of the old address,
                // once for addition of the new address.
                unsafe {
                    (self.callback)(
                        CassHostListenerEvent::CASS_HOST_LISTENER_EVENT_REMOVE,
                        CassInet::from(old_address.ip()),
                        self.data,
                    );
                    (self.callback)(
                        CassHostListenerEvent::CASS_HOST_LISTENER_EVENT_ADD,
                        CassInet::from(new_address.ip()),
                        self.data,
                    );
                }
            }
            _ => (), // Unknown event, do nothing.
        };
    }
}

// NOTE:
// This is seemingly duplicated wrt cql_types/inet.rs.
// The truth is that this CassInet is different that the one in cql_types/inet.rs,
// because they come from different modules generated by bindgen.
// TODO: unify these two CassInet definitions, perhaps by generating all bindgen defs
// in one module only.
impl From<IpAddr> for CassInet {
    fn from(ip_addr: IpAddr) -> Self {
        match ip_addr {
            IpAddr::V4(v4_addr) => {
                let mut address = [0; 16];
                address[0..(CassInetLength::CASS_INET_V4 as usize)]
                    .copy_from_slice(&v4_addr.octets());

                CassInet {
                    address,
                    address_length: CassInetLength::CASS_INET_V4 as u8,
                }
            }
            IpAddr::V6(v6_addr) => {
                let mut address = [0; 16];
                address[0..(CassInetLength::CASS_INET_V6 as usize)]
                    .copy_from_slice(&v6_addr.octets());

                CassInet {
                    address,
                    address_length: CassInetLength::CASS_INET_V6 as u8,
                }
            }
        }
    }
}
