name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  # Should include `INTEGRATION_TEST_BIN` from the `Makefile`
  # TODO: Remove `build/libscylla-cpp-driver.*` after https://github.com/scylladb/cpp-rs-driver/issues/164 is fixed.
  INTEGRATION_TEST_BIN: |
    build/cassandra-integration-tests
    build/libscylla-cpp-driver.*
  INTEGRATION_TEST_BIN_CACHE_KEY: integration-test-bin-${{ github.sha }}
  # Goes to `Makefile` to let it pickup cached binary
  DONT_REBUILD_INTEGRATION_BIN: true
  CCM_LOGS_PATTERN: /tmp/ccm*/ccm*/node*/logs/*

jobs:
  build-lint-and-unit-test:
    name: Build, lint and run unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update apt cache
        run: sudo apt-get update -y

      - name: Install dependencies
        run: make install-build-dependencies

      - name: Check
        run: make check

      - name: Run unit and proxy tests
        run: make run-test-unit

      - name: Run examples
        run: make run-examples-scylla

      - name: Build integration test binary
        id: build-integration-test-bin
        run: make build-integration-test-bin

      - name: Save integration test binary
        uses: actions/cache/save@v4
        id: save-integration-test-bin
        with:
          path: ${{ env.INTEGRATION_TEST_BIN }}
          key: ${{ env.INTEGRATION_TEST_BIN_CACHE_KEY }}

  scylla-integration-tests:
    name: Scylla ITs
    runs-on: ubuntu-22.04
    needs: [build-lint-and-unit-test]
    timeout-minutes: 90

    strategy:
      matrix:
        include:
          - scylla-version: LTS-LATEST
            scylla-filter: '^[0-9]{4}$.^[0-9]+$.^[0-9]+$ and LAST.1.LAST'
          - scylla-version: LTS-PRIOR
            scylla-filter: '^[0-9]{4}$.^[0-9]+$.^[0-9]+$ and LAST-1.1.LAST'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Update apt cache
        run: sudo apt-get update -y

      - name: Install CCM
        run: |
          make install-ccm-if-missing

      - name: Get scylla version
        id: scylla-version
        uses: scylladb-actions/get-version@v0.4.5
        with:
          source: dockerhub-imagetag
          repo: scylladb/scylla
          filters: ${{ matrix.scylla-filter }}

      - name: Resolve scylla version
        id: scylla-version-value
        run: echo "value=${{ fromJson(steps.scylla-version.outputs.versions)[0] }}" | tee -a "$GITHUB_OUTPUT"

      - name: Pull CCM image from the cache
        uses: actions/cache/restore@v4
        id: pull-image
        with:
          path: ~/.ccm/scylla-repository
          key: image-scylla-${{ runner.os }}-${{ steps.scylla-version-value.outputs.value }}

      - name: Download Scylla (${{ steps.scylla-version-value.outputs.value }}) image
        if: steps.pull-image.outputs.cache-hit != 'true'
        run: SCYLLA_VERSION="release:${{ steps.scylla-version-value.outputs.value }}" make download-ccm-scylla-image

      - name: Save CCM image cache
        uses: actions/cache/save@v4
        if: steps.pull-image.outputs.cache-hit != 'true'
        with:
          path: ~/.ccm/scylla-repository
          key: image-scylla-${{ runner.os }}-${{ steps.scylla-version-value.outputs.value }}

      - name: Pull integration test binary
        uses: actions/cache/restore@v4
        id: restore-integration-test-bin
        with:
          path: ${{ env.INTEGRATION_TEST_BIN }}
          key: ${{ env.INTEGRATION_TEST_BIN_CACHE_KEY }}
          # Otherwise the binary won't be present, and test workflows will attempt to build it,
          # failing due to build dependencies not being installed in the test workflow.
          # It's better to fail early; this is a transient error that can be fixed by re-running
          # the build-lint-and-unit-test job.
          fail-on-cache-miss: true

      - name: Prepare environment
        run: make update-rust-tooling prepare-integration-test

      - name: Run integration tests on Scylla ${{ steps.scylla-version-value.outputs.value }}
        id: run-integration-tests
        run: SCYLLA_VERSION="release:${{ steps.scylla-version-value.outputs.value }}" make run-test-integration-scylla

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: steps.run-integration-tests.outcome == 'failure'
        with:
          name: test-logs-scylla-${{ matrix.scylla-version }}
          path: ./log/*

      - name: Upload CCM logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ccm-log-scylla-${{ matrix.scylla-version }}
          path: ${{ env.CCM_LOGS_PATTERN }}

  cassandra-integration-tests:
    runs-on: ubuntu-22.04
    needs: [build-lint-and-unit-test]

    strategy:
      matrix:
        cassandra-version: [3-LATEST]
        java-version: [8]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "adopt"

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Update apt cache
        run: sudo apt-get update -y

      - name: Install CCM
        run: make install-ccm-if-missing

      - name: Get cassandra version
        id: cassandra-version
        uses: scylladb-actions/get-version@v0.4.5
        with:
          source: github-tag
          repo: apache/cassandra
          prefix: cassandra-
          out-no-prefix: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          filters: '^[0-9]+$.^[0-9]+$.^[0-9]+$ and 3.LAST.LAST'

      - name: Resolve cassandra version
        id: cassandra-version-value
        run: |
          value=${{ fromJson(steps.cassandra-version.outputs.versions)[0] }}
          echo "value=${value#cassandra-}" | tee -a "$GITHUB_OUTPUT"

      - name: Pull CCM image from the cache
        uses: actions/cache/restore@v4
        id: pull-image
        with:
          path: ~/.ccm/repository
          key: image-cassandra-${{ runner.os }}-${{ steps.cassandra-version-value.outputs.value }}

      - name: Download Cassandra (${{ steps.cassandra-version-value.outputs.value }}) image
        if: steps.pull-image.outputs.cache-hit != 'true'
        run: CASSANDRA_VERSION="${{ steps.cassandra-version-value.outputs.value }}" make download-ccm-cassandra-image

      - name: Save CCM image cache
        uses: actions/cache/save@v4
        if: steps.pull-image.outputs.cache-hit != 'true'
        with:
          path: ~/.ccm/repository
          key: image-cassandra-${{ runner.os }}-${{ steps.cassandra-version-value.outputs.value }}

      - name: Pull integration test binary
        uses: actions/cache/restore@v4
        id: restore-integration-test-bin
        with:
          path: ${{ env.INTEGRATION_TEST_BIN }}
          key: ${{ env.INTEGRATION_TEST_BIN_CACHE_KEY }}
          # Otherwise the binary won't be present, and test workflows will attempt to build it,
          # failing due to build dependencies not being installed in the test workflow.
          # It's better to fail early; this is a transient error that can be fixed by re-running
          # the build-lint-and-unit-test job.
          fail-on-cache-miss: true

      - name: Prepare environment
        run: make update-rust-tooling prepare-integration-test

      - name: Run integration tests on Cassandra ${{ steps.cassandra-version.outputs.value }}
        id: run-integration-tests
        run: CASSANDRA_VERSION="${{ steps.cassandra-version.outputs.value }}" make run-test-integration-cassandra

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: steps.run-integration-tests.outcome == 'failure'
        with:
          name: test-logs-cassandra-${{ matrix.cassandra-version }}
          path: ./log/*

      - name: Upload CCM logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ccm-log-cassandra-${{ matrix.java-version }}-${{ matrix.cassandra-version }}
          path: ${{ env.CCM_LOGS_PATTERN }}
